---
abstract: 'Atom Publishing Protocol implementation'
author:
  - 'Takeru INOUE, <takeru.inoue _ gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Atompub
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  DateTime: 0
  DateTime::Format::W3CDTF: 0
  DateTime::TimeZone: 0
  Digest::SHA: 0
  File::Slurp: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  MIME::Base64: 0
  MIME::Types: 0
  Module::Build::Compat: 0
  Perl6::Export::Attrs: 0
  Test::Perl::Critic: 0
  Time::Local: 0
  URI::Escape: 0
  XML::Atom::Service: 0.016
  perl: 5.6.0
  version: 0.74
resources:
  license: http://dev.perl.org/licenses/
version: 0.003007
