---
name: Atompub
version: 0.1.8
author:
  - 'Takeru INOUE <takeru.inoue _ gmail.com>'
abstract: Atom Publishing Protocol implementation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Class::Accessor::Lvalue::Fast: 0
  DateTime: 0
  Digest::SHA1: 0
  File::Slurp: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  MIME::Base64: 0
  MIME::Types: 0
  Perl6::Export::Attrs: 0
  Test::More: 0
  Test::Perl::Critic: 0
  URI::Escape: 0
  XML::Atom::Service: 0.15.4
  version: 0
provides:
  Atompub:
    file: lib/Atompub.pm
    version: 0.1.8
  Atompub::Client:
    file: lib/Atompub/Client.pm
  Atompub::Client::Cache:
    file: lib/Atompub/Client.pm
  Atompub::Client::Cache::Resource:
    file: lib/Atompub/Client.pm
  Atompub::Client::Info:
    file: lib/Atompub/Client.pm
  Atompub::DateTime:
    file: lib/Atompub/DateTime.pm
  Atompub::DateTime::TimeZone:
    file: lib/Atompub/DateTime.pm
  Atompub::MediaType:
    file: lib/Atompub/MediaType.pm
  Atompub::Server:
    file: lib/Atompub/Server.pm
  Atompub::Util:
    file: lib/Atompub/Util.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
